---
apiVersion: v1
data:
  SASL_JAAS_CONFIG: {{ .Values.saslJaasConfig }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-sasl-secret
type: Opaque
---
apiVersion: v1
data:
  auth: |-
    {{ .Files.Get "htpassword" | b64enc }}
kind: Secret
metadata:
  name: rest-auth-secret
type: Opaque
