---
apiVersion: v1
data:
  SASL_JAAS_CONFIG: {{ .Values.saslJaasConfig }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-sasl-secret
type: Opaque
---
apiVersion: v1
data:
  CONSUMER_JAAS_CONFIG: {{ .Values.consumerBasicAuthConfig }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-secret
type: Opaque
---
apiVersion: v1
data:
  SASL_JAAS_CONFIG: {{ .Values.saslJaasConfig }}
  auth: |-
    {{ .Files.Get "htpassword" | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-htpass-secret
type: Opaque
